// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'disabled': string;
  'dragOver': string;
  'dragPlaceholder': string;
  'dragPlaceholder_show': string;
  'draggableWrap': string;
  'dragging': string;
  'timer': string;
  'timersList': string;
}
export const cssExports: CssExports;
export default cssExports;
