// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'button': string;
  'disabled': string;
  'header': string;
  'name': string;
  'time': string;
  'timeButtons': string;
  'time_divider': string;
  'time_input': string;
  'timer': string;
}
export const cssExports: CssExports;
export default cssExports;
