// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'linkButton': string;
  'suggest': string;
  'templates': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
