// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addTimer': string;
  'app': string;
  'darkTheme': string;
  'dimBackground': string;
  'generalButtons': string;
  'header': string;
  'header_buttons': string;
  'header_dropdownWrap': string;
  'header_title': string;
  'hide': string;
  'timersList': string;
}
export const cssExports: CssExports;
export default cssExports;
