// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'body': string;
  'button': string;
  'buttons': string;
  'name': string;
  'time': string;
  'time_divider': string;
  'time_item': string;
  'timerEnded': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
